In [66]:
import torch
import math


num_timesteps = 1000
# t = torch.randint(0, diffusion.num_timesteps, (x.shape[0],), device=device)
# num_timesteps 作为时间步范围，随机生成长度与 x 相等的向量
t = torch.randint(0, num_timesteps, (4,), device='cpu')

t

tensor([358, 728, 904, 442])

In [67]:

dim = 7
max_period = 1000
half = dim // 2
# 按照指数衰竭生成频率张量
freqs = torch.exp(
    -math.log(max_period) * torch.arange(start=0, end=half, dtype=torch.float32) / half
)
freqs


tensor([1.0000, 0.1000, 0.0100])

In [68]:
# 将 t 转置，将 t 和 freqs 扩展一个维度,并且相乘
args = t[:, None].float() * freqs[None]
print(t[:, None].float())
print(freqs[None])
print(args)


tensor([[358.],
        [728.],
        [904.],
        [442.]])
tensor([[1.0000, 0.1000, 0.0100]])
tensor([[358.0000,  35.8000,   3.5800],
        [728.0000,  72.8000,   7.2800],
        [904.0000,  90.4000,   9.0400],
        [442.0000,  44.2000,   4.4200]])


In [69]:
# 将余弦和正弦 cat 到一起，对于奇数维度，在最后一列（dim = -1），补上 0
print(torch.cos(args))
print(torch.sin(args))
embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
print(embedding[:, :1])
print(torch.zeros_like(embedding[:, :1]))
if dim % 2:
    embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)

embedding

tensor([[ 0.9900, -0.3224, -0.9054],
        [ 0.6604, -0.8560,  0.5430],
        [ 0.7118, -0.7608, -0.9269],
        [-0.5698,  0.9764, -0.2882]])
tensor([[-0.1411, -0.9466, -0.4245],
        [-0.7509, -0.5170,  0.8397],
        [-0.7023,  0.6489,  0.3754],
        [ 0.8218,  0.2160, -0.9576]])
tensor([[ 0.9900],
        [ 0.6604],
        [ 0.7118],
        [-0.5698]])
tensor([[0.],
        [0.],
        [0.],
        [0.]])


tensor([[ 0.9900, -0.3224, -0.9054, -0.1411, -0.9466, -0.4245,  0.0000],
        [ 0.6604, -0.8560,  0.5430, -0.7509, -0.5170,  0.8397,  0.0000],
        [ 0.7118, -0.7608, -0.9269, -0.7023,  0.6489,  0.3754,  0.0000],
        [-0.5698,  0.9764, -0.2882,  0.8218,  0.2160, -0.9576,  0.0000]])